dewey_system = {
    "000": [
        "000 – Computer science, information & general works",
        "001 – Knowledge",
        "002 – The book",
        "003 – Systems",
        "004 – Data processing & computer science",
        "005 – Computer programming, programs & data",
        "006 – Special computer methods",
        "007 – Not assigned or no longer used",
        "008 – Not assigned or no longer used",
        "009 – Not assigned or no longer used"
    ],
    "010": [
        "010 – Bibliography",
        "011 – Bibliographies",
        "012 – Bibliographies of individuals",
        "013 – Not assigned or no longer used",
        "014 – Bibliographies of anonymous & pseudonymous works",
        "015 – Bibliographies of works from specific places",
        "016 – Bibliographies of works on specific subjects",
        "017 – General subject catalogs",
        "018 – Catalogs arranged by author, date, etc.",
        "019 – Dictionary catalogs"
    ],
    "020": [
        "020 – Library & information sciences",
        "021 – Library relationships",
        "022 – Administration of physical plant",
        "023 – Personnel management",
        "024 – Not assigned or no longer used",
        "025 – Library operations",
        "026 – Libraries for specific subjects",
        "027 – General libraries",
        "028 – Reading & use of other information media",
        "029 – Not assigned or no longer used"
    ],
    "030": [
        "030 – Encyclopedias & books of facts",
        "031 – General encyclopedic works in American English",
        "032 – General encyclopedic works in English",
        "033 – General encyclopedic works in other Germanic languages",
        "034 – General encyclopedic works in French, Occitan & Catalan",
        "035 – General encyclopedic works in Italian, Romanian & related languages",
        "036 – General encyclopedic works in Spanish & Portuguese",
        "037 – General encyclopedic works in Slavic languages",
        "038 – General encyclopedic works in Scandinavian languages",
        "039 – General encyclopedic works in other languages"
    ],
    "040": [
        "040 – (Unassigned)"
    ],
    "050": [
        "050 – Magazines, journals & serials",
        "051 – Magazines, journals & serials in American English",
        "052 – Magazines, journals & serials in English",
        "053 – Magazines, journals & serials in other Germanic languages",
        "054 – Magazines, journals & serials in French, Occitan & Catalan",
        "055 – Magazines, journals & serials in Italian, Romanian & related languages",
        "056 – Magazines, journals & serials in Spanish & Portuguese",
        "057 – Magazines, journals & serials in Slavic languages",
        "058 – Magazines, journals & serials in Scandinavian languages",
        "059 – Magazines, journals & serials in other languages"
    ],
    "060": [
        "060 – Associations, organizations & museums",
        "061 – Organizations in North America",
        "062 – Organizations in British Isles; in England",
        "063 – Organizations in central Europe; in Germany",
        "064 – Organizations in France & Monaco",
        "065 – Organizations in Italy & adjacent territories",
        "066 – Organizations in Iberian Peninsula & adjacent islands",
        "067 – Organizations in eastern Europe; in Russia",
        "068 – Organizations in other geographic areas",
        "069 – Museum science"
    ],
    "070": [
        "070 – News media, journalism & publishing",
        "071 – Newspapers in North America",
        "072 – Newspapers in British Isles; in England",
        "073 – Newspapers in central Europe; in Germany",
        "074 – Newspapers in France & Monaco",
        "075 – Newspapers in Italy & adjacent territories",
        "076 – Newspapers in Iberian Peninsula & adjacent islands",
        "077 – Newspapers in eastern Europe; in Russia",
        "078 – Newspapers in Scandinavia",
        "079 – Newspapers in other geographic areas"
    ],
    "080": [
        "080 – Quotations",
        "081 – Collections in American English",
        "082 – Collections in English",
        "083 – Collections in other Germanic languages",
        "084 – Collections in French, Occitan & Catalan",
        "085 – Collections in Italian, Romanian & related languages",
        "086 – Collections in Spanish & Portuguese",
        "087 – Collections in Slavic languages",
        "088 – Collections in Scandinavian languages",
        "089 – Collections in other languages"
    ],
    "090": [
        "090 – Manuscripts & rare books",
        "091 – Manuscripts",
        "092 – Block books",
        "093 – Incunabula",
        "094 – Printed books",
        "095 – Books notable for bindings",
        "096 – Books notable for illustrations",
        "097 – Books notable for ownership or origin",
        "098 – Prohibited works, forgeries & hoaxes",
        "099 – Books notable for format"
    ],

    "100": [
        "100 – Philosophy",
        "101 – Theory of philosophy",
        "102 – Miscellany of philosophy",
        "103 – Dictionaries & encyclopedias of philosophy",
        "104 – Special topics in philosophy",
        "105 – Serial publications of philosophy",
        "106 – Organizations & management of philosophy",
        "107 – Education, research, related topics of philosophy",
        "108 – Kinds of persons in philosophy",
        "109 – Historical & collected persons treatment in philosophy"
    ],
    "110": [
        "110 – Metaphysics",
        "111 – Ontology",
        "112 – No longer used—formerly Methodology",
        "113 – Cosmology",
        "114 – Space",
        "115 – Time",
        "116 – Change",
        "117 – Structure",
        "118 – Force and energy",
        "119 – Number and quantity"
    ],
    "120": [
        "120 – Epistemology, causation, humankind",
        "121 – Epistemology, theory of knowledge",
        "122 – Causation",
        "123 – Determinism & indeterminism",
        "124 – Teleology",
        "125 – Infinity",
        "126 – The self",
        "127 – The unconscious & the subconscious",
        "128 – Humankind",
        "129 – Origin & destiny of individual souls"
    ],
    "130": [
        "130 – Paranormal phenomena",
        "131 – Occult methods for achieving well-being",
        "132 – No longer used—formerly Mental derangements",
        "133 – Specific topics in parapsychology & occultism",
        "133.1 – Parapsychological & occult methods for achieving well-being",
        "133.2 – Specific topics in parapsychology & occultism",
        "133.3 – Divinatory graphology",
        "133.4 – Divination",
        "133.5 – Astrology",
        "133.6 – Apparitions",
        "133.7 – Demonology & witchcraft",
        "133.8 – Spiritualism",
        "133.9 – Unexplained phenomena",
        "134 – No longer used—formerly Mesmerism & Clairvoyance",
        "135 – Dreams & mysteries",
        "136 – No longer used—formerly Mental characteristics",
        "137 – Divinatory graphology",
        "138 – Physiognomy",
        "139 – Phrenology"
    ],
    "140": [
        "140 – Philosophical schools of thought",
        "141 – Idealism & related systems",
        "142 – Critical philosophy",
        "143 – Bergsonism & intuitionism",
        "144 – Humanism & related systems",
        "145 – Sensationalism (Empiricism)",
        "146 – Naturalism & related systems",
        "147 – Pantheism & related systems",
        "148 – Eclecticism, liberalism, traditionalism",
        "149 – Other philosophical systems"
    ],
    "150": [
        "150 – Psychology",
        "150 – General psychology",
        "151 – No longer used—formerly Intellect",
        "152 – Perception, movement, emotions & drives",
        "152.1 – Sensory perception",
        "152.2 – Psychophysiology (General)",
        "152.3 – Specific aspects of consciousness & perception",
        "152.4 – Movement",
        "152.5 – Emotions",
        "152.6 – Affection",
        "152.7 – Will",
        "152.8 – Determinants of behavior",
        "152.9 – Specific manifestations of higher mental processes",
        "153 – Conscious mental processes & intelligence",
        "153.1 – Attention",
        "153.2 – Memory",
        "153.3 – Association of ideas",
        "153.4 – Thought processes",
        "153.5 – Intelligence",
        "153.6 – Higher mental processes",
        "153.7 – Thought & thinking",
        "153.8 – Abnormal processes",
        "153.9 – Specific states of consciousness",
        "154 – Subconscious & altered states",
        "154.1 – Subconscious",
        "154.2 – Hypnotism",
        "154.3 – Sleep & dreams",
        "154.4 – Altered states of consciousness",
        "154.5 – Hallucinations & illusions",
        "154.6 – Trance & ecstasy",
        "154.7 – No longer used—formerly Spiritual states",
        "154.8 – Specific altered states",
        "154.9 – No longer used—formerly Mysticism",
        "155 – Differential & developmental psychology",
        "155.1 – Differential psychology",
        "155.2 – Individual psychology",
        "155.3 – Comparative psychology",
        "155.4 – Developmental psychology",
        "155.5 – Child psychology",
        "155.6 – Adolescent psychology",
        "155.7 – Adult psychology",
        "155.8 – Geropsychology",
        "155.9 – Aging psychology",
        "156 – Comparative psychology",
        "156.1 – Comparative psychology (General)",
        "156.2 – Comparative cognition",
        "156.3 – Comparative learning",
        "156.4 – Comparative behavior",
        "156.5 – Comparative sensory & perceptual processes",
        "156.6 – Comparative emotion",
        "156.7 – Comparative motivation",
        "156.8 – Comparative social processes",
        "156.9 – Other comparative psychology topics",
        "157 – Emotions",
        "158 – Applied psychology",
        "158.1 – Psychotherapy",
        "158.2 – Counseling & mental health services",
        "158.3 – Self-help & practical guides",
        "158.4 – Life skills & personal growth",
        "158.5 – Interpersonal relations",
        "158.6 – Workplace psychology",
        "158.7 – Consumer psychology",
        "158.8 – Community psychology",
        "158.9 – Miscellaneous applications",
        "159 – Miscellaneous applications of psychology",
        "159.1 – Theories & systems",
        "159.2 – Measurement & testing",
        "159.3 – Mental testing",
        "159.4 – No longer used—formerly Personality tests",
        "159.5 – No longer used—formerly Character tests",
        "159.6 – No longer used—formerly Aptitude tests",
        "159.7 – No longer used—formerly Vocational tests",
        "159.8 – No longer used—formerly Interest tests",
        "159.9 – No longer used—formerly Miscellaneous tests"
    ],
    "160": [
        "160 – Logic",
        "160 – Logic",
        "161 – Inductive logic",
        "162 – Deductive logic",
        "163 – Analogy",
        "164 – Not assigned or no longer used",
        "165 – Fallacies & sources of error",
        "166 – Syllogisms",
        "167 – Hypotheses",
        "168 – Argument & persuasion",
        "169 – Analogy"
    ],
    "170": [
        "170 – Ethics",
        "170 – Ethics (General)",
        "171 – Ethical systems",
        "172 – Political ethics",
        "173 – Ethics of family relationships",
        "174 – Occupational ethics",
        "174.1 – Medical ethics",
        "174.2 – Business ethics",
        "174.3 – Legal ethics",
        "174.4 – Media ethics",
        "174.5 – Educational ethics",
        "174.6 – Scientific ethics",
        "174.7 – Engineering ethics",
        "174.8 – Environmental ethics",
        "174.9 – Miscellaneous occupational ethics",
        "175 – Ethics of recreation & leisure",
        "176 – Ethics of sex & reproduction",
        "177 – Ethics of social relations",
        "178 – Ethics of consumption",
        "179 – Other ethical norms"
    ],
    "180": [
        "180 – Ancient, medieval & Eastern philosophy",
        "180 – Ancient, medieval & Eastern philosophy",
        "181 – Eastern philosophy",
        "181.1 – Indian philosophy",
        "181.2 – Chinese philosophy",
        "181.3 – Japanese philosophy",
        "181.4 – Other Eastern philosophies",
        "181.5 – South East Asian philosophy",
        "181.6 – Central Asian philosophy",
        "181.7 – Korean philosophy",
        "181.8 – Tibetan philosophy",
        "181.9 – Mongolian philosophy",
        "182 – Pre-Socratic Greek philosophies",
        "183 – Socratic & related philosophies",
        "184 – Platonic philosophy",
        "185 – Aristotelian philosophy",
        "186 – Skeptic & Neoplatonic philosophies",
        "187 – Epicurean philosophy",
        "188 – Stoic philosophy",
        "189 – Medieval Western philosophy"
    ],
    "190": [
        "190 – Modern Western philosophy",
        "190 – Modern Western philosophy",
        "191 – Modern Western philosophy of the United States & Canada",
        "192 – Modern Western philosophy of the British Isles",
        "193 – Modern Western philosophy of Germany & Austria",
        "194 – Modern Western philosophy of France",
        "195 – Modern Western philosophy of Italy",
        "196 – Modern Western philosophy of Spain & Portugal",
        "197 – Modern Western philosophy of Russia",
        "198 – Modern Western philosophy of Scandinavia",
        "199 – Modern Western philosophy of other geographic areas"
    ],
    "200": [
        "200 – Religion",
        "201 – Philosophy & theory of religion",
        "202 – Miscellany of religion",
        "203 – Public worship & other practices",
        "204 – Religious experience, life & practice",
        "205 – Religious ethics",
        "206 – Leaders & organization",
        "207 – Missions & religious education",
        "208 – Sources",
        "209 – Sects & reform movements"
    ],
    "210": [
        "210 – Philosophy & theory of religion",
        "211 – Concepts of God",
        "212 – Existence, knowability & attributes of God",
        "213 – Creation",
        "214 – Theodicy",
        "215 – Science & religion",
        "216 – No longer used—formerly Evil",
        "217 – No longer used—formerly Prayer",
        "218 – Humankind",
        "219 – No longer used—formerly Analogies"
    ],
    "220": [
        "220 – The Bible",
        "221 – Old Testament (Tanakh)",
        "222 – Historical books of Old Testament",
        "223 – Poetic books of Old Testament",
        "224 – Prophetic books of Old Testament",
        "225 – New Testament",
        "226 – Gospels & Acts",
        "227 – Epistles",
        "228 – Revelation (Apocalypse)",
        "229 – Apocrypha & pseudepigrapha"
    ],
    "230": [
        "230 – Christianity",
        "231 – God",
        "232 – Jesus Christ & his family",
        "233 – Humankind",
        "234 – Salvation & grace",
        "235 – Spiritual beings",
        "236 – Eschatology",
        "237 – No longer used—formerly Future state",
        "238 – Creeds & catechisms",
        "239 – Apologetics & polemics"
    ],
    "240": [
        "240 – Christian practice & observance",
        "241 – Christian ethics",
        "242 – Devotional literature",
        "243 – Evangelistic writings for individuals",
        "244 – No longer used—formerly Collections of hymns",
        "245 – No longer used—formerly Texts of hymns",
        "246 – Use of art in Christianity",
        "247 – Church furnishings & articles",
        "248 – Christian experience, practice, life",
        "249 – Christian observances in family life"
    ],
    "250": [
        "250 – Christian pastoral practice & religious orders",
        "251 – Preaching (Homiletics)",
        "252 – Texts of sermons",
        "253 – Pastoral office & work (Pastoral theology)",
        "254 – Parish government & administration",
        "255 – Religious congregations & orders",
        "256 – No longer used—formerly Religious societies",
        "257 – No longer used—formerly Parochial schools, libraries, etc.",
        "258 – No longer used—formerly Parish care",
        "259 – Pastoral care of families, specific groups of people"
    ],
    "260": [
        "260 – Christian organization, social work & worship",
        "261 – Social theology",
        "262 – Ecclesiology",
        "263 – Times, places of religious observance",
        "264 – Public worship",
        "265 – Sacraments, other rites & acts",
        "266 – Missions",
        "267 – Associations for religious work",
        "268 – Religious education",
        "269 – Spiritual renewal"
    ],
    "270": [
        "270 – History of Christianity",
        "271 – Religious orders in church history",
        "272 – Persecutions in church history",
        "273 – Heresies in church history",
        "274 – History of Christianity in Europe",
        "275 – History of Christianity in Asia",
        "276 – History of Christianity in Africa",
        "277 – History of Christianity in North America",
        "278 – History of Christianity in South America",
        "279 – History of Christianity in other areas"
    ],
    "280": [
        "280 – Christian denominations",
        "281 – Early church & Eastern churches",
        "282 – Roman Catholic Church",
        "283 – Anglican churches",
        "284 – Protestants of Continental origin",
        "285 – Presbyterian, Reformed & Congregational",
        "286 – Baptist, Disciples of Christ & Adventist",
        "287 – Methodist & related churches",
        "288 – No longer used—formerly Unitarianism",
        "289 – Other denominations & sects"
    ],
    "290": [
        "290 – Other religions",
        "291 – Comparative religion",
        "292 – Greek & Roman religion",
        "293 – Germanic religion",
        "294 – Religions of Indic origin",
        "295 – Religions of East & Southeast Asian origin",
        "296 – Judaism",
        "297 – Islam, Bábism & Bahá'í Faith",
        "298 – No longer used—formerly Mormonism & related faiths",
        "299 – Religions not provided for elsewhere"
    ],
        "300": [
        "300 – Social sciences, sociology & anthropology",
        "301 – Sociology & anthropology",
        "302 – Social interaction",
        "303 – Social processes",
        "304 – Factors affecting social behavior",
        "305 – Social groups",
        "306 – Culture & institutions",
        "307 – Communities",
        "308 – No longer used—formerly Polygraphy",
        "309 – No longer used—formerly History of sociology"
    ],
    "310": [
        "310 – Statistics",
        "311 – No longer used—formerly Theory & methods",
        "312 – No longer used—formerly Population",
        "313 – No longer used—formerly Special topics",
        "314 – General statistics of Europe",
        "315 – General statistics of Asia",
        "316 – General statistics of Africa",
        "317 – General statistics of North America",
        "318 – General statistics of South America",
        "319 – General statistics of other areas"
    ],
    "320": [
        "320 – Political science",
        "321 – Systems of governments & states",
        "322 – Relation of state to organized groups",
        "323 – Civil & political rights",
        "324 – The political process",
        "325 – International migration & colonization",
        "326 – Slavery & emancipation",
        "327 – International relations",
        "328 – The legislative process",
        "329 – Not assigned or no longer used"
    ],
    "330": [
        "330 – Economics",
        "331 – Labor economics",
        "332 – Financial economics",
        "333 – Economics of land & energy",
        "334 – Cooperatives",
        "335 – Socialism & related systems",
        "336 – Public finance",
        "337 – International economics",
        "338 – Production",
        "339 – Macroeconomics & related topics"
    ],
    "340": [
        "340 – Law",
        "341 – International law",
        "342 – Constitutional & administrative law",
        "343 – Military, defense, public property, public finance, tax, commerce (trade), industrial law",
        "344 – Social, labor, welfare, & related law",
        "345 – Criminal law",
        "346 – Private law",
        "347 – Civil procedure & courts",
        "348 – Laws, regulations, cases",
        "349 – Law of specific jurisdictions & areas"
    ],
    "350": [
        "350 – Public administration & military science",
        "351 – Public administration",
        "352 – General considerations of public administration",
        "353 – Specific fields of public administration",
        "354 – Central governments",
        "355 – Military science",
        "356 – Infantry forces & warfare",
        "357 – Mounted forces & warfare",
        "358 – Air & other specialized forces",
        "359 – Sea forces & warfare"
    ],
    "360": [
        "360 – Social problems & social services",
        "361 – Social problems & social welfare in general",
        "362 – Social welfare problems & services",
        "363 – Other social problems & services",
        "364 – Criminology",
        "365 – Penal & related institutions",
        "366 – Associations",
        "367 – General clubs",
        "368 – Insurance",
        "369 – Miscellaneous kinds of associations"
    ],
    "370": [
        "370 – Education",
        "371 – Schools & their activities; special education",
        "372 – Elementary education",
        "373 – Secondary education",
        "374 – Adult education",
        "375 – Curricula",
        "376 – No longer used—formerly Education of women",
        "377 – No longer used—formerly Ethical education",
        "378 – Higher education",
        "379 – Public policy issues in education"
    ],
    "380": [
        "380 – Commerce, communications & transportation",
        "381 – Commerce (Trade)",
        "382 – International commerce (Foreign trade)",
        "383 – Postal communication",
        "384 – Communications; Telecommunication",
        "385 – Railroad transportation",
        "386 – Inland waterway & ferry transportation",
        "387 – Water, air & space transportation",
        "388 – Transportation; Ground transportation",
        "389 – Metrology & standardization"
    ],
    "390": [
        "390 – Customs, etiquette & folklore",
        "391 – Costume & personal appearance",
        "392 – Customs of life cycle & domestic life",
        "393 – Death customs",
        "394 – General customs",
        "395 – Etiquette (Manners)",
        "396 – No longer used—formerly Women's position & treatment",
        "397 – No longer used—formerly Outcast studies",
        "398 – Folklore",
        "399 – Customs of war & diplomacy"
    ],
    "400": [
        "400 – Language",
        "401 – Philosophy & theory of language",
        "402 – Miscellany",
        "403 – Dictionaries & encyclopedias",
        "404 – Special topics of language",
        "405 – Serial publications",
        "406 – Organizations & management",
        "407 – Education, research & related topics",
        "408 – With respect to kinds of persons",
        "409 – Geographical & historical treatment"
    ],
    "410": [
        "410 – Linguistics",
        "411 – Writing systems",
        "412 – Etymology",
        "413 – Dictionaries",
        "414 – Phonology & phonetics",
        "415 – Grammar",
        "416 – Prosody (versification)",
        "417 – Dialectology & historical linguistics",
        "418 – Standard usage; Applied linguistics",
        "419 – Sign languages"
    ],
    "420": [
        "420 – English & Old English (Anglo-Saxon)",
        "421 – Writing system & phonology of standard English",
        "422 – Etymology of standard English",
        "423 – Dictionaries of standard English",
        "424 – No longer used—formerly English thesauruses",
        "425 – Grammar of standard English",
        "426 – No longer used—formerly Prosody of standard English",
        "427 – Historical & geographical variations, modern nongeographic variations of English",
        "428 – Standard English usage & applied linguistics",
        "429 – Old English (Anglo-Saxon)"
    ],
    "430": [
        "430 – Germanic languages; German",
        "431 – Writing systems, phonology, phonetics of standard German",
        "432 – Etymology of standard German",
        "433 – Dictionaries of standard German",
        "434 – No longer used—formerly German thesauruses",
        "435 – Grammar of standard German",
        "436 – No longer used—formerly Prosody of standard German",
        "437 – Historical & geographic variations, modern nongeographic variations of German",
        "438 – Standard German usage",
        "439 – Other Germanic languages"
    ],
    "440": [
        "440 – Romance languages; French",
        "441 – Writing systems, phonology, phonetics of standard French",
        "442 – Etymology of standard French",
        "443 – Dictionaries of standard French",
        "444 – No longer used—formerly French thesauruses",
        "445 – Grammar of standard French",
        "446 – No longer used—formerly Prosody of standard French",
        "447 – Historical & geographic variations, modern nongeographic variations of French",
        "448 – Standard French usage",
        "449 – Provençal & Catalan"
    ],
    "450": [
        "450 – Italian, Romanian & related languages",
        "451 – Writing systems, phonology, phonetics of standard Italian",
        "452 – Etymology of standard Italian",
        "453 – Dictionaries of standard Italian",
        "454 – No longer used—formerly Italian thesauruses",
        "455 – Grammar of standard Italian",
        "456 – No longer used—formerly Prosody of standard Italian",
        "457 – Historical & geographic variations, modern nongeographic variations of Italian",
        "458 – Standard Italian usage",
        "459 – Romanian & related languages"
    ],
    "460": [
        "460 – Spanish & Portuguese languages",
        "461 – Writing systems, phonology, phonetics of standard Spanish",
        "462 – Etymology of standard Spanish",
        "463 – Dictionaries of standard Spanish",
        "464 – No longer used—formerly Spanish thesauruses",
        "465 – Grammar of standard Spanish",
        "466 – No longer used—formerly Prosody of standard Spanish",
        "467 – Historical & geographic variations, modern nongeographic variations of Spanish",
        "468 – Standard Spanish usage",
        "469 – Portuguese"
    ],
    "470": [
        "470 – Italic languages; Latin",
        "471 – Writing systems, phonology, phonetics of classical Latin",
        "472 – Etymology of classical Latin",
        "473 – Dictionaries of classical Latin",
        "474 – No longer used—formerly Latin thesauruses",
        "475 – Grammar of classical Latin",
        "476 – No longer used—formerly Prosody of classical Latin",
        "477 – Historical & geographic variations, modern nongeographic variations of Latin",
        "478 – Classical Latin usage",
        "479 – Other Italic languages"
    ],
    "480": [
        "480 – Hellenic languages; Classical Greek",
        "481 – Writing systems, phonology, phonetics of classical Greek",
        "482 – Etymology of classical Greek",
        "483 – Dictionaries of classical Greek",
        "484 – No longer used—formerly Greek thesauruses",
        "485 – Grammar of classical Greek",
        "486 – No longer used—formerly Prosody of classical Greek",
        "487 – Historical & geographic variations, modern nongeographic variations of Greek",
        "488 – Classical Greek usage",
        "489 – Other Hellenic languages"
    ],
    "490": [
        "490 – Other languages",
        "491 – East Indo-European & Celtic languages",
        "492 – Afro-Asiatic languages; Semitic languages",
        "493 – Non-Semitic Afro-Asiatic languages",
        "494 – Altic, Uralic, Hyperborean, Dravidian & other languages",
        "495 – Languages of East & Southeast Asia",
        "496 – African languages",
        "497 – North American native languages",
        "498 – South American native languages",
        "499 – Austronesian & other languages of Oceania, Austro-Asiatic languages"
    ],
        "500": [
        "500 – Science",
        "501 – Philosophy & theory",
        "502 – Miscellany",
        "503 – Dictionaries & encyclopedias",
        "504 – Not assigned or no longer used",
        "505 – Serial publications",
        "506 – Organizations & management",
        "507 – Education, research & related topics",
        "508 – Natural history",
        "509 – Historical, geographic & persons treatment"
    ],
    "510": [
        "510 – Mathematics",
        "511 – General principles of mathematics",
        "512 – Algebra",
        "513 – Arithmetic",
        "514 – Topology",
        "515 – Analysis",
        "516 – Geometry",
        "517 – Not assigned or no longer used",
        "518 – Numerical analysis",
        "519 – Probabilities & applied mathematics"
    ],
    "520": [
        "520 – Astronomy",
        "521 – Celestial mechanics",
        "522 – Techniques, equipment & materials",
        "523 – Specific celestial bodies & phenomena",
        "524 – Not assigned or no longer used",
        "525 – Earth (Astronomical geography)",
        "526 – Mathematical geography",
        "527 – Celestial navigation",
        "528 – Ephemerides",
        "529 – Chronology"
    ],
    "530": [
        "530 – Physics",
        "531 – Classical mechanics; Solid mechanics",
        "532 – Fluid mechanics; Liquid mechanics",
        "533 – Gas mechanics",
        "534 – Sound & related vibrations",
        "535 – Light & related radiation",
        "536 – Heat",
        "537 – Electricity & electronics",
        "538 – Magnetism",
        "539 – Modern physics; Quantum mechanics; Nuclear physics"
    ],
    "540": [
        "540 – Chemistry",
        "541 – Physical chemistry",
        "542 – Techniques, equipment & materials",
        "543 – Analytical chemistry",
        "544 – Not assigned or no longer used",
        "545 – Not assigned or no longer used",
        "546 – Inorganic chemistry",
        "547 – Organic chemistry",
        "548 – Crystallography",
        "549 – Mineralogy"
    ],
    "550": [
        "550 – Earth sciences & geology",
        "551 – Geology, hydrology, meteorology",
        "552 – Petrology",
        "553 – Economic geology",
        "554 – Earth sciences of Europe",
        "555 – Earth sciences of Asia",
        "556 – Earth sciences of Africa",
        "557 – Earth sciences of North America",
        "558 – Earth sciences of South America",
        "559 – Earth sciences of other areas"
    ],
    "560": [
        "560 – Fossils & prehistoric life",
        "561 – Paleobotany; Fossil microorganisms",
        "562 – Fossil invertebrates",
        "563 – Fossil primitive phyla",
        "564 – Fossil Mollusca & Molluscoidea",
        "565 – Fossil Arthropoda",
        "566 – Fossil Chordata",
        "567 – Fossil cold-blooded vertebrates; Fossil fishes",
        "568 – Fossil Aves (birds)",
        "569 – Fossil Mammalia"
    ],
    "570": [
        "570 – Life sciences; Biology",
        "571 – Physiology & related subjects",
        "572 – Biochemistry",
        "573 – Specific physiological systems in animals",
        "574 – Not assigned or no longer used",
        "575 – Specific parts of & physiological systems in plants",
        "576 – Genetics & evolution",
        "577 – Ecology",
        "578 – Natural history of organisms",
        "579 – Microorganisms, fungi & algae"
    ],
    "580": [
        "580 – Plants (Botany)",
        "581 – Specific topics in natural history of plants",
        "582 – Plants noted for specific vegetative characteristics & flowers",
        "583 – Magnoliopsida (Dicotyledons)",
        "584 – Liliopsida (Monocotyledons)",
        "585 – Pinophyta (Conifers)",
        "586 – Gnetophyta & Magnoliophyta (Angiosperms)",
        "587 – Pteridophyta (Ferns)",
        "588 – Bryophyta",
        "589 – Miscellaneous plants"
    ],
    "590": [
        "590 – Animals (Zoology)",
        "591 – Specific topics in natural history of animals",
        "592 – Invertebrates",
        "593 – Protozoa, Echinodermata, related phyla",
        "594 – Mollusca & Molluscoidea",
        "595 – Other invertebrates",
        "596 – Vertebrata (Craniata, Vertebrates)",
        "597 – Cold-blooded vertebrates; Fishes",
        "598 – Aves (Birds)",
        "599 – Mammalia (Mammals)"
    ],
    "600": [
        "600 – Technology",
        "601 – Philosophy & theory",
        "602 – Miscellany",
        "603 – Dictionaries & encyclopedias",
        "604 – Special topics",
        "605 – Serial publications",
        "606 – Organizations",
        "607 – Education, research & related topics",
        "608 – Inventions & patents",
        "609 – Historical, geographic & persons treatment"
    ],
    "610": [
        "610 – Medicine & health",
        "611 – Human anatomy, cytology & histology",
        "612 – Human physiology",
        "613 – Personal health & safety",
        "614 – Incidence & prevention of disease",
        "615 – Pharmacology & therapeutics",
        "616 – Diseases",
        "617 – Surgery & related medical specialties",
        "618 – Gynecology, obstetrics, pediatrics & geriatrics",
        "619 – Experimental medicine"
    ],
    "620": [
        "620 – Engineering & allied operations",
        "621 – Applied physics",
        "622 – Mining & related operations",
        "623 – Military & nautical engineering",
        "624 – Civil engineering",
        "625 – Engineering of railroads & roads",
        "626 – Not assigned or no longer used",
        "627 – Hydraulic engineering",
        "628 – Sanitary engineering",
        "629 – Other branches of engineering"
    ],
    "630": [
        "630 – Agriculture & related technologies",
        "631 – Techniques, equipment & materials",
        "632 – Plant injuries, diseases & pests",
        "633 – Field & plantation crops",
        "634 – Orchards, fruits & forestry",
        "635 – Garden crops (Horticulture)",
        "636 – Animal husbandry",
        "637 – Processing dairy & related products",
        "638 – Insect culture",
        "639 – Hunting, fishing & conservation"
    ],
    "640": [
        "640 – Home & family management",
        "641 – Food & drink",
        "642 – Meals & table service",
        "643 – Housing & household equipment",
        "644 – Household utilities",
        "645 – Household furnishings",
        "646 – Sewing, clothing & personal living",
        "647 – Management of public households",
        "648 – Housekeeping",
        "649 – Child rearing & home care of sick"
    ],
    "650": [
        "650 – Management & auxiliary services",
        "651 – Office services",
        "652 – Processes of written communication",
        "653 – Shorthand",
        "654 – Not assigned or no longer used",
        "655 – Not assigned or no longer used",
        "656 – Not assigned or no longer used",
        "657 – Accounting",
        "658 – General management",
        "659 – Advertising & public relations"
    ],
    "660": [
        "660 – Chemical engineering",
        "661 – Industrial chemicals technology",
        "662 – Explosives, fuels technology",
        "663 – Beverage technology",
        "664 – Food technology",
        "665 – Industrial oils, fats, waxes, gases technology",
        "666 – Ceramic & allied technologies",
        "667 – Cleaning, color, coating technologies",
        "668 – Technology of other organic products",
        "669 – Metallurgy"
    ],
    "670": [
        "670 – Manufacturing",
        "671 – Metalworking & metal products",
        "672 – Iron, steel, other iron alloys",
        "673 – Nonferrous metals",
        "674 – Lumber processing, wood products, cork",
        "675 – Leather & fur processing",
        "676 – Pulp & paper technology",
        "677 – Textiles",
        "678 – Elastomers & elastomer products",
        "679 – Other products of specific materials"
    ],
    "680": [
        "680 – Manufacture for specific uses",
        "681 – Precision instruments & other devices",
        "682 – Small forge work (Blacksmithing)",
        "683 – Hardware & household appliances",
        "684 – Furnishings & home workshops",
        "685 – Leather, fur goods & related products",
        "686 – Printing & related activities",
        "687 – Clothing & accessories",
        "688 – Other final products & packaging",
        "689 – Not assigned or no longer used"
    ],
    "690": [
        "690 – Buildings",
        "691 – Building materials",
        "692 – Auxiliary construction practices",
        "693 – Specific materials & purposes",
        "694 – Wood construction; Carpentry",
        "695 – Roof covering",
        "696 – Utilities",
        "697 – Heating, ventilating, air-conditioning",
        "698 – Detail finishing",
        "699 – Not assigned or no longer used"
    ],
    "700": [
        "700 – Arts & recreation",
        "701 – Philosophy & theory",
        "702 – Miscellany",
        "703 – Dictionaries & encyclopedias",
        "704 – Special topics",
        "705 – Serial publications",
        "706 – Organizations & management",
        "707 – Education, research & related topics",
        "708 – Galleries, museums, private collections",
        "709 – Historical, geographic & persons treatment"
    ],
    "710": [
        "710 – Landscaping & area planning",
        "711 – Area planning (Civic art)",
        "712 – Landscape architecture",
        "713 – Landscape architecture of trafficways",
        "714 – Water features",
        "715 – Woody plants",
        "716 – Herbaceous plants",
        "717 – Structures in landscape architecture",
        "718 – Landscape design of cemeteries",
        "719 – Natural landscapes"
    ],
    "720": [
        "720 – Architecture",
        "721 – Architectural structure",
        "722 – Architecture from earliest times to ca. 300",
        "723 – Architecture from ca. 300 to 1399",
        "724 – Architecture from 1400",
        "725 – Public structures",
        "726 – Buildings for religious & related purposes",
        "727 – Buildings for education & research",
        "728 – Residential & related buildings",
        "729 – Design & decoration"
    ],
    "730": [
        "730 – Sculpture, ceramics & metalwork",
        "731 – Processes, forms & subjects of sculpture",
        "732 – Sculpture to ca. 500",
        "733 – Greek, Etruscan & Roman sculpture",
        "734 – Sculpture from ca. 500 to 1399",
        "735 – Sculpture from 1400",
        "736 – Carving & carvings",
        "737 – Numismatics & sigillography",
        "738 – Ceramics",
        "739 – Art metalwork"
    ],
    "740": [
        "740 – Drawing & decorative arts",
        "741 – Drawing & drawings",
        "742 – Perspective",
        "743 – Drawing & drawings by subject",
        "744 – Not assigned or no longer used",
        "745 – Decorative arts",
        "746 – Textile arts",
        "747 – Interior decoration",
        "748 – Glass",
        "749 – Furniture & accessories"
    ],
    "750": [
        "750 – Painting & paintings",
        "751 – Techniques, equipment & materials",
        "752 – Color",
        "753 – Symbolism, allegory, mythology, legend",
        "754 – Genre paintings",
        "755 – Religion & religious symbolism",
        "756 – Not assigned or no longer used",
        "757 – Human figures",
        "758 – Other subjects",
        "759 – Historical, geographic & persons treatment"
    ],
    "760": [
        "760 – Graphic arts; Printmaking & prints",
        "761 – Relief processes (Block printing)",
        "762 – Planographic processes",
        "763 – Lithographic processes",
        "764 – Chromolithography & serigraphy",
        "765 – Metal engraving",
        "766 – Mezzotinting",
        "767 – Etching & drypoint",
        "768 – Not assigned or no longer used",
        "769 – Prints"
    ],
    "770": [
        "770 – Photography, computer art, film, video",
        "771 – Techniques, equipment & materials",
        "772 – Metallic salt processes",
        "773 – Pigment processes of printing",
        "774 – Holography",
        "775 – Digital photography",
        "776 – Computer art (Digital art)",
        "777 – Cinematography & videography",
        "778 – Fields & kinds of photography",
        "779 – Photographs"
    ],
    "780": [
        "780 – Music",
        "781 – General principles & musical forms",
        "782 – Vocal music",
        "783 – Music for single voices; The voice",
        "784 – Instruments & Instrumental ensembles",
        "785 – Ensembles with one instrument per part",
        "786 – Keyboard & other instruments",
        "787 – Stringed instruments (Chordophones)",
        "788 – Wind instruments (Aerophones)",
        "789 – Unassigned or no longer used"
    ],
    "790": [
        "790 – Recreational & performing arts",
        "791 – Public performances",
        "792 – Stage presentations",
        "793 – Indoor games & amusements",
        "794 – Indoor games of skill",
        "795 – Games of chance",
        "796 – Athletic & outdoor sports & games",
        "797 – Aquatic & air sports",
        "798 – Equestrian sports & animal racing",
        "799 – Fishing, hunting & shooting"
    ],
    "800": [
        "800 – Literature, rhetoric & criticism",
        "801 – Philosophy & theory",
        "802 – Miscellany",
        "803 – Dictionaries & encyclopedias",
        "804 – Not assigned or no longer used",
        "805 – Serial publications",
        "806 – Organizations & management",
        "807 – Education, research & related topics",
        "808 – Rhetoric & collections of literature",
        "809 – Literary history & criticism"
    ],
    "810": [
        "810 – American literature in English",
        "811 – American poetry in English",
        "812 – American drama in English",
        "813 – American fiction in English",
        "814 – American essays in English",
        "815 – American speeches in English",
        "816 – American letters in English",
        "817 – American humor & satire in English",
        "818 – American miscellaneous writings in English",
        "819 – No longer used—formerly reserved for American literature in other languages"
    ],
    "820": [
        "820 – English & Old English literatures",
        "821 – English poetry",
        "822 – English drama",
        "823 – English fiction",
        "824 – English essays",
        "825 – English speeches",
        "826 – English letters",
        "827 – English humor & satire",
        "828 – English miscellaneous writings",
        "829 – Old English (Anglo-Saxon)"
    ],
    "830": [
        "830 – German & related literatures",
        "831 – German poetry",
        "832 – German drama",
        "833 – German fiction",
        "834 – German essays",
        "835 – German speeches",
        "836 – German letters",
        "837 – German humor & satire",
        "838 – German miscellaneous writings",
        "839 – Other Germanic literatures"
    ],
    "840": [
        "840 – Literatures of Romance languages",
        "841 – French poetry",
        "842 – French drama",
        "843 – French fiction",
        "844 – French essays",
        "845 – French speeches",
        "846 – French letters",
        "847 – French humor & satire",
        "848 – French miscellaneous writings",
        "849 – Occitan & Catalan literatures"
    ],
    "850": [
        "850 – Italian, Romanian & related literatures",
        "851 – Italian poetry",
        "852 – Italian drama",
        "853 – Italian fiction",
        "854 – Italian essays",
        "855 – Italian speeches",
        "856 – Italian letters",
        "857 – Italian humor & satire",
        "858 – Italian miscellaneous writings",
        "859 – Romanian & related literatures"
    ],
    "860": [
        "860 – Spanish & Portuguese literatures",
        "861 – Spanish poetry",
        "862 – Spanish drama",
        "863 – Spanish fiction",
        "864 – Spanish essays",
        "865 – Spanish speeches",
        "866 – Spanish letters",
        "867 – Spanish humor & satire",
        "868 – Spanish miscellaneous writings",
        "869 – Portuguese literature"
    ],
    "870": [
        "870 – Italic literatures; Latin literature",
        "871 – Latin poetry",
        "872 – Latin dramatic poetry & drama",
        "873 – Latin epic poetry & fiction",
        "874 – Latin lyric poetry",
        "875 – Latin speeches",
        "876 – Latin letters",
        "877 – Latin humor & satire",
        "878 – Latin miscellaneous writings",
        "879 – Literatures of other Italic languages"
    ],
    "880": [
        "880 – Hellenic literatures; Classical Greek",
        "881 – Classical Greek poetry",
        "882 – Classical Greek dramatic poetry & drama",
        "883 – Classical Greek epic poetry & fiction",
        "884 – Classical Greek lyric poetry",
        "885 – Classical Greek speeches",
        "886 – Classical Greek letters",
        "887 – Classical Greek humor & satire",
        "888 – Classical Greek miscellaneous writings",
        "889 – Modern Greek literature"
    ],
    "890": [
        "890 – Literatures of other languages",
        "891 – East Indo-European & Celtic literatures",
        "892 – Afro-Asiatic literatures; Semitic literatures",
        "893 – Non-Semitic Afro-Asiatic literatures",
        "894 – Literatures of Altaic, Uralic, Hyperborean, Dravidian & other languages",
        "895 – Literatures of East & Southeast Asia",
        "896 – African literatures",
        "897 – Literatures of North American native languages",
        "898 – Literatures of South American native languages",
        "899 – Literatures of Austronesian & other languages"
    ],
    "900": [
        "900 – History & geography",
        "901 – Philosophy & theory of history",
        "902 – Miscellany of history",
        "903 – Dictionaries & encyclopedias of history",
        "904 – Collected accounts of events",
        "905 – Serial publications of history",
        "906 – Organizations & management of history",
        "907 – Education, research, related topics of history",
        "908 – History with respect to kinds of persons",
        "909 – World history"
    ],
    "910": [
        "910 – Geography & travel",
        "911 – Historical geography",
        "912 – Graphic representations of earth",
        "913 – Geography of & travel in ancient world",
        "914 – Geography of & travel in Europe",
        "915 – Geography of & travel in Asia",
        "916 – Geography of & travel in Africa",
        "917 – Geography of & travel in North America",
        "918 – Geography of & travel in South America",
        "919 – Geography of & travel in other areas"
    ],
    "920": [
        "920 – Biography, genealogy, insignia",
        "921 – Not assigned or no longer used",
        "922 – Not assigned or no longer used",
        "923 – Not assigned or no longer used",
        "924 – Not assigned or no longer used",
        "925 – Not assigned or no longer used",
        "926 – Not assigned or no longer used",
        "927 – Not assigned or no longer used",
        "928 – Not assigned or no longer used",
        "929 – Genealogy, names, insignia"
    ],
    "930": [
        "930 – History of ancient world (to ca. 499)",
        "931 – History of ancient world; China",
        "932 – History of ancient world; Egypt",
        "933 – History of ancient world; Palestine",
        "934 – History of ancient world; India",
        "935 – History of ancient world; Mesopotamia & Iranian Plateau",
        "936 – History of ancient world; Europe north & west of Italy",
        "937 – History of ancient world; Italy & adjacent territories",
        "938 – History of ancient world; Greece",
        "939 – History of ancient world; Other parts of ancient world"
    ],
    "940": [
        "940 – History of Europe",
        "941 – History of British Isles",
        "942 – History of England & Wales",
        "943 – History of central Europe; Germany",
        "944 – History of France & Monaco",
        "945 – History of Italy, San Marino, Vatican City, Malta",
        "946 – History of Iberian Peninsula & adjacent islands",
        "947 – History of eastern Europe; Russia",
        "948 – History of northern Europe; Scandinavia",
        "949 – History of other parts of Europe"
    ],
    "950": [
        "950 – History of Asia; Far East",
        "951 – History of China & adjacent areas",
        "952 – History of Japan",
        "953 – History of Arabian Peninsula & adjacent areas",
        "954 – History of India & South Asia",
        "955 – History of Iran",
        "956 – History of Middle East (Near East)",
        "957 – History of Siberia (Asiatic Russia)",
        "958 – History of Central Asia",
        "959 – History of Southeast Asia"
    ],
    "960": [
        "960 – History of Africa",
        "961 – History of Tunisia & Libya",
        "962 – History of Egypt & Sudan",
        "963 – History of Ethiopia",
        "964 – History of Morocco & Canary Islands",
        "965 – History of Algeria",
        "966 – History of West Africa & offshore islands",
        "967 – History of Central Africa & offshore islands",
        "968 – History of southern Africa",
        "969 – History of South Indian Ocean islands"
    ],
    "970": [
        "970 – History of North America",
        "971 – History of Canada",
        "972 – History of Middle America; Mexico",
        "973 – History of United States",
        "974 – History of northeastern United States",
        "975 – History of southeastern United States",
        "976 – History of south central United States",
        "977 – History of north central United States",
        "978 – History of western United States",
        "979 – History of Great Basin & Pacific Slope"
    ],
    "980": [
        "980 – History of South America",
        "981 – History of Brazil",
        "982 – History of Argentina",
        "983 – History of Chile",
        "984 – History of Bolivia",
        "985 – History of Peru",
        "986 – History of Colombia & Ecuador",
        "987 – History of Venezuela",
        "988 – History of Guiana",
        "989 – History of Paraguay & Uruguay"
    ],
    "990": [
        "990 – History of other areas",
        "991 – Not assigned or no longer used",
        "992 – Not assigned or no longer used",
        "993 – History of New Zealand",
        "994 – History of Australia",
        "995 – History of Melanesia; New Guinea",
        "996 – History of Other parts of Pacific Polynesia",
        "997 – History of Atlantic Ocean islands",
        "998 – History of Arctic islands & Antarctica",
        "999 – Extraterrestrial worlds"
    ]
}    

